services:
  foundry-hardhat-vertigo:
   build:
    context: .
    dockerfile: DockerfileDev
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock