services:
  go-service:
    init: true
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
    - type: bind
      source: ./.zshrc
      target: /root/.zshrc
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
