services:
  frax-dev-service: 
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: DockerfileDev
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock