services:
  go-service:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    command: sh ./terminal-config.sh
  foundry-service:
    entrypoint:
    - sleep
    - infinity
    image: ghcr.io/foundry-rs/foundry
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

