services:
  foundry-service: 
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: DockerfileDev
    init: true
    volumes:
    - type: bind
      source: ./.zshrc
      target: /root/.zshrc
    - type: bind
      source: ./codespaces.zsh-theme
      target: /root/codespaces.zsh-theme
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
